<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29773" started-at="2018-02-02T06:40:56Z" finished-at="2018-02-02T06:41:26Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="29773" started-at="2018-02-02T06:40:56Z" finished-at="2018-02-02T06:41:26Z">
      <class name="com.TestCases.Test123">
        <test-method status="FAIL" signature="testcase123(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.TestCases.Test123@d8355a8]" name="testcase123" duration-ms="23361" started-at="2018-02-02T12:10:57Z" data-provider="getdata" finished-at="2018-02-02T12:11:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CustomerA]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[DescriptionA]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[cradio1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:Sucess msg not Displayed...]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:Sucess msg not Displayed...at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.library.library.verifysucessmsg(library.java:55)at com.TestCases.Test123.testcase123(Test123.java:21)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase123 -->
        <test-method status="PASS" signature="testcase123(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.TestCases.Test123@d8355a8]" name="testcase123" duration-ms="2806" started-at="2018-02-02T12:11:20Z" data-provider="getdata" finished-at="2018-02-02T12:11:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CustomerB]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[DescriptionB]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[cradio2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase123 -->
        <test-method status="PASS" signature="testcase123(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.TestCases.Test123@d8355a8]" name="testcase123" duration-ms="2921" started-at="2018-02-02T12:11:23Z" data-provider="getdata" finished-at="2018-02-02T12:11:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CustomerC]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[DescriptionC]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[cradio3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase123 -->
      </class> <!-- com.TestCases.Test123 -->
      <class name="com.TestCases.OpenAndCloseBrowser">
        <test-method status="PASS" signature="bsuite()[pri:0, instance:com.TestCases.OpenAndCloseBrowser@46d56d67]" name="bsuite" is-config="true" duration-ms="4836" started-at="2018-02-02T12:10:51Z" finished-at="2018-02-02T12:10:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bsuite -->
        <test-method status="PASS" signature="asuite()[pri:0, instance:com.TestCases.OpenAndCloseBrowser@46d56d67]" name="asuite" is-config="true" duration-ms="837" started-at="2018-02-02T12:11:26Z" finished-at="2018-02-02T12:11:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asuite -->
      </class> <!-- com.TestCases.OpenAndCloseBrowser -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
